ft #175743403: Added login page
atlp-rwanda/space-bn-frontend pull request #12
Opened 2020-12-04 15:44 UTC by marcelniyi

### **What does this PR do?**
Implement login page.

### **Description of Task to be completed?**
- Implementation of a login page feature.

- Implementation of responsiveness of a login page.

### **How should this be manually tested?**

 - Clone the repository
 - Do `npm install` to install required modules.
 - Do `npm run start` to start the server.
 - Do `npm run test` to run the tests.
 - Browse the app at `localhost:3000`

### **Any background context you want to provide?**
N/A

### **What are the relevant Pivotal Tracker stories**?
#175743403

### **Screenshots**

<img width="1273" alt="Screen Shot 2020-12-04 at 17 30 27" src="https://user-images.githubusercontent.com/52769059/101183359-17d83780-3658-11eb-98f7-562836fa25ab.png">

2020-12-04 19:37 UTC, SimonImanigirimpuhwe requested changes
Could you please consider having the same background for the `Pattern` and the background of the page? because the page background looks somehow having low opacity than the `Pattern` background and leads to showing it extremity.

You also need to write `**tests**` for your page.

2020-12-05 09:59 UTC, PatrickNiyogitare28 requested changes
You can try to increase the either the height or padding of the login button. to be of the same size with the inputs. Then we be good to go! Anyway most of the required work is done which is good.

2020-12-05 09:59 UTC, PatrickNiyogitare28 commented
> Could you please consider having the same background for the `Pattern` and the background of the page? because the page background looks somehow having low opacity than the `Pattern` background and leads to showing it extremity.
> 
> You also need to write **`tests`** for your page.

2020-12-06 09:57 UTC, SamuelSabasNayo requested changes
As @PatrickNiyogitare28 requested, try to increase the spacing between the Login button, Login with Google, and Login with Facebook. You can consider the Signup page.

2020-12-06 19:00 UTC, SimonImanigirimpuhwe requested changes
Good job but we still need tests of  **`Login component`**
Consider also solving conflicting files

2020-12-06 19:00 UTC, SimonImanigirimpuhwe commented on src/shared/styles/LoginStyles.js
> +})
Good improvement on the pattern

2020-12-07 03:38 UTC, PatrickNiyogitare28 approved these changes

2020-12-07 04:31 UTC, SamuelSabasNayo approved these changes

2020-12-07 06:39 UTC, ConstantineMaliza requested changes
Great work @marcelniyi  You can build login look the same as signup page to avoid the difference look. correct it as @PatrickNiyogitare28 and @SimonImanigirimpuhwe  said

2020-12-07 15:50 UTC, merged