#175743429-ft-Create-request
atlp-rwanda/space-bn-frontend pull request #13
Opened 2020-12-07 14:19 UTC by ConstantineMaliza

#### What does this PR do?
 
#### Description of Task to be completed?
Implementation of a login page feature.

#### Implementation of responsiveness of a login page.

#### How should this be manually tested?
Clone the repository
- Do `npm install` to install required modules.
- Do `npm run start` to start the server.
-Do `npm run test` to run the tests.
- Browse the app at `localhost:3000/booking`
#### Any background context you want to provide?
N/A

#### What are the relevant Pivotal Tracker stories?
#175743429
#### Screenshots
![image](https://user-images.githubusercontent.com/50266109/101361577-d1791780-38a7-11eb-804f-cbeaa43050d0.png)

2020-12-07 16:34 UTC, PatrickNiyogitare28 approved these changes
Good work!

2020-12-07 16:46 UTC, SamuelSabasNayo approved these changes

2020-12-08 06:34 UTC, marcelniyi approved these changes

2020-12-15 16:03 UTC, PatrickNiyogitare28 approved these changes
The feature is well implemented!

2020-12-15 16:05 UTC, PatrickNiyogitare28 requested changes
Good work @ConstantineMaliza! but your work is failing to build you can try rebasing as well as resolving the build errors.

2020-12-17 15:45 UTC, closed without merging