Fix home page
atlp-rwanda/space-bn-frontend pull request #15
Opened 2020-12-11 05:36 UTC by PatrickNiyogitare28

### Bug description
- Fix  common theme.
- Added new logo.
- Fix horizontal alignement of home page content
- Proper import of  Header and Footer components.

### Root cause
- Default material UI background.
- Login and Signup bottom contents was hidden by Footer

### Solution description
- A new logo was designed.
- White them was added globally to override material default theme.
- Header and Footer components were imported in other pages.

### What are the relevant Pivotal Tracker stories?
- [#176048315](https://www.pivotaltracker.com/n/projects/2476677)
- [#176037767](https://www.pivotaltracker.com/n/projects/2476677)
- [#176038228](https://www.pivotaltracker.com/n/projects/2476677)

### Screenshots (if appropriate)
![home2](https://user-images.githubusercontent.com/54368821/101867113-15f40400-3b83-11eb-9aaf-92109a27a388.png)

### Questions
- N/A

2020-12-11 09:47 UTC, SimonImanigirimpuhwe requested changes
Good job! But here are few thing to consider.
1. Since  you changed the `general theme` from  `#fafafa` to`#ffffff`you can also change the background of the **Pattern** of the `Signup page`.
2. Another thing is that could you please remove the scroll behavior on the `Login page`

2020-12-11 15:18 UTC, Malaba6 commented
Good job Patrick. However there are a few changes you'll be required to make:
1.
![1607699362596](https://user-images.githubusercontent.com/50101879/101920449-df4ad780-3bdc-11eb-92a5-4e706bdb03f3.png)

2.
![1607698106704](https://user-images.githubusercontent.com/50101879/101920660-220caf80-3bdd-11eb-82e4-17d1be4d13c3.png)

2020-12-11 15:40 UTC, Malaba6 requested changes

2020-12-11 15:40 UTC, Malaba6 commented on src/components/Footer/index.js
> +        // position: 'fixed',
Remove these commented out lines

2020-12-11 15:40 UTC, Malaba6 commented on src/components/Footer/index.js
> +        // bottom: 0,
And here!

2020-12-14 04:26 UTC, PatrickNiyogitare28 commented
> Good job Patrick. However there are a few changes you'll be required to make:
> 1.
> ![1607699362596](https://user-images.githubusercontent.com/50101879/101920449-df4ad780-3bdc-11eb-92a5-4e706bdb03f3.png)
> 
> 
> ![1607698106704](https://user-images.githubusercontent.com/50101879/101920660-220caf80-3bdd-11eb-82e4-17d1be4d13c3.png)

This was successfully resolved

2020-12-14 04:32 UTC, PatrickNiyogitare28 commented
Dear @SimonImanigirimpuhwe 
Your issue 1, was solved successfully.
Issue 2, was not solved since contents are not fitting in the screen except for mac. but I kept consistance between two pages signup and login.

2020-12-14 04:34 UTC, PatrickNiyogitare28 commented
Dear @Malaba6,
Your issues where worked on and now they are resolved successfully.
About the navigation menu items spacing will be found in the PR for @SamuelSabasNayo since he worked on it.

2020-12-14 04:59 UTC, SamuelSabasNayo approved these changes

2020-12-14 05:00 UTC, marcelniyi approved these changes

2020-12-14 05:01 UTC, SamuelSabasNayo commented
We would like to ask our managers to merge our PR for us to proceed smoothly.

2020-12-14 11:45 UTC, merged