#176168716 chore(context): setup context for state management
atlp-rwanda/space-bn-frontend pull request #19
Opened 2020-12-16 08:23 UTC by SimonImanigirimpuhwe

2020-12-16 09:18 UTC, Malaba6 requested changes

2020-12-16 09:18 UTC, malaba6 commented on src/contexts/AuthContext.js
> +    }
Plz include the user avatar aswell in the user context

2020-12-16 09:18 UTC, malaba6 commented on src/helpers/toasts.js
> +console.log(toast)
Plz remove this console.log line

2020-12-16 09:18 UTC, malaba6 commented on src/views/Login/Login.js
> +          toaster('You are logged in', 'succes')
Typo here, success not succes

2020-12-16 09:18 UTC, malaba6 commented on src/views/Login/Login.js
> +          console.log('logged')
Remove this console line

2020-12-17 08:58 UTC, PatrickNiyogitare28 approved these changes

2020-12-17 09:04 UTC, SamuelSabasNayo approved these changes

2020-12-18 04:53 UTC, joshwambere reviewed
When you input the wrong credentials it exactly tells you what you got wrong, eg: if you enter the wrong password it tells you provided the wrong password I think for security reasons it shouldn't

2020-12-19 07:24 UTC, merged